all:
	g++ -pedantic -w -Wall -std=c++11 players_hands_state_per_color.cpp -o players_hands_state_per_color.out
	g++ -pedantic -w -Wall -std=c++11 stair_state.cpp -o stair_state.out
#	./analise_combinatorial 10 5 2> debug.err
#	@cat debug.err
