TARGET=main.tex
SOURCES=apresentacao.tex forma_extensa.tex pesquisa.tex

all:$(TARGET)
	pdflatex $(TARGET) $(SOURCES)
	pdflatex $(TARGET) $(SOURCES)

clean:
	rm -v *.nav *.snm *.toc *.vrb *.out *.log *.aux
